import type { Metadata } from 'next';
import { LegalPage } from '@/components/marketing/legal-page';
export const metadata: Metadata={title:'Privacy Policy',description:'How ADH Background Remover handles uploaded images, browser history, sessions and processing records.',alternates:{canonical:'/privacy-policy'}};
export default function Page(){return <LegalPage title="Privacy Policy" intro="This policy describes information handled by American Design Hub when you use ADH Background Remover, its API, and its browser extension. The image compressor is a separate service with its own privacy policy." sections={[
 {id:'images',title:'1. Your images',paragraphs:['Images you submit are sent to the server for background removal. The current ADH service processes image bytes in memory and returns the result to your browser; it does not create a permanent server image archive. Closing the page does not delete copies you have downloaded.','The background-removal workflow does not use your uploads to train models or publish them as showcase images. Only upload material you are entitled to process, and avoid including sensitive information that is unnecessary for your task.']},
 {id:'browser',title:'2. History on your device',paragraphs:['The browser can save original and processed images, thumbnails and related details in IndexedDB so you can revisit recent work. This history is limited to the most recent 50 items. These local copies can remain after you close the page.','Use the history controls to remove saved items, or clear this site’s data in your browser. Clearing browser data also removes local preferences and session information; it does not by itself erase server processing records.']},
 {id:'records',title:'3. Processing records and API keys',paragraphs:['The server records processing metadata, including the submitted filename, output dimensions, file size, processing duration and timestamp. Recent processing history is capped at 100 records per visitor identifier. Usage counters support quotas and the dashboard. Avoid putting sensitive information in filenames.','When an API key is created, the service retains its label, identifier, hashed secret and related usage information. Protect the secret and revoke keys you no longer need. The current browser workflow uses anonymous sessions and does not require an email address, password or payment details.']},
 {id:'cookies',title:'4. Cookies and essential storage',paragraphs:['An essential cookie named adh_session identifies your anonymous session and links it to usage and API-key records. It is configured to last up to one year. You can remove it through browser settings, though doing so may prevent you from accessing records associated with that session.','Browser storage supports history and preferences. The core application does not include advertising trackers. Hosting infrastructure may separately produce technical access and error logs needed for service operation and security.']},
 {id:'extension',title:'5. Browser extension',paragraphs:['The extension sends the image you choose to the configured background-removal endpoint. Its settings, including a configured API key and recent activity, can be stored locally by your browser. If you configure a different server, that operator’s policies apply to the information it receives.']},
 {id:'purpose',title:'6. Use, access and retention',paragraphs:['Information is used to carry out your request, display your history, enforce usage limits and investigate service errors or abuse. Hosting and infrastructure providers may handle information necessary to operate the service, and disclosure may be required by law.','Browser image history remains until it is removed or displaced by newer items. Server metadata, usage records and key records are separate from images and are not automatically deleted when a request finishes. Contact us to request deletion or information about records associated with your session; we may need enough information to verify that the request is yours.']},
 {id:'choices',title:'7. Your choices and rights',paragraphs:['Depending on the law that applies to you, you may have rights to access, correct, delete or restrict use of personal information, or to complain to a data-protection authority. Contact us to exercise those rights. Do not send your API-key secret in a support request.','We do not request children’s personal information. If you believe a child has submitted personal information that should be removed, contact us.']},
 {id:'changes',title:'8. Other sites and policy updates',paragraphs:['Links to American Design Hub, the image compressor and other websites open services with their own practices. Review their policies before submitting information.','Changes to this policy will be reflected in the date above. Any material change to how uploads are stored or used should be described here before that change is introduced.']}
 ]}/>;}
