import type { Metadata } from 'next';
import { LegalPage } from '@/components/marketing/legal-page';
export const metadata: Metadata={title:'Terms and Conditions',description:'Terms for using the ADH Background Remover website, API and extension.',alternates:{canonical:'/terms'}};
export default function Page(){return <LegalPage title="Terms and Conditions" intro="These terms govern your use of ADH Background Remover, operated by American Design Hub. By using the tool or its API, you agree to these terms. If you do not agree, please do not use the service." sections={[
 {id:'service',title:'1. The service',paragraphs:['ADH Background Remover automatically separates an image’s subject from its background and provides tools to prepare the result for download. Available formats, file limits and usage allowances are described in the tool and on the pricing page.','The current service is free within its usage limits. No paid subscription or checkout is currently offered here. Separate ADH products, including the image compressor, have their own terms and any applicable charges.']},
 {id:'content',title:'2. Your content and permission',paragraphs:['You retain your rights in the images you submit. You give us permission to process them and return the requested results, only as needed to provide the service.','You must have the rights and any necessary consent to upload and edit an image. Removing a background does not remove copyright, trademark, privacy or other rights belonging to someone else. You are responsible for how you use or publish the result.']},
 {id:'review',title:'3. Review your results',paragraphs:['Automatic segmentation can omit details or leave parts of a background, particularly with transparent materials, reflections and fine edges. Inspect the output before relying on it or publishing it. Keep your original files.','Local history is a convenience, not a backup service. Browser cleanup, device changes and storage limits can remove it. Download and securely store any files you need to keep.']},
 {id:'use',title:'4. Responsible use',paragraphs:['Do not use the service for unlawful content, infringement, unauthorised access, or activity that harms other users. Do not evade quotas, interfere with security controls or send traffic intended to overload the service.','Keep API keys confidential and revoke compromised keys. You are responsible for requests made using keys you control. We may limit or suspend access to protect the service or address misuse.']},
 {id:'privacy',title:'5. Information and privacy',paragraphs:['Our Privacy Policy describes server processing, browser image history and retained metadata. Using the service does not require you to give up ownership of your images. Do not upload confidential or sensitive material unless you are authorised to send it for processing.']},
 {id:'availability',title:'6. Availability and changes',paragraphs:['We may maintain, update or discontinue features and adjust limits. Availability, processing speed and the suitability of a result are not guaranteed. We will provide notice of material changes where reasonably practicable.','The service is supplied as available, without guarantees beyond those required by applicable law. To the extent permitted by law, American Design Hub is not responsible for indirect losses arising from interruptions, incorrect results or loss of files. Nothing in these terms excludes liability or consumer rights that cannot legally be excluded.']},
 {id:'third-parties',title:'7. Other products and software',paragraphs:['Links to external services do not make those services part of this agreement. Open-source components remain subject to their respective licences; these terms do not override rights those licences grant.']},
 {id:'updates',title:'8. Updates and questions',paragraphs:['We will update the date on this page when these terms change. Please review the current version before continued use. If a change is unacceptable to you, you may stop using the service.','Contact us first if you have a concern so we can try to resolve it. These terms do not restrict any right you have to seek a remedy under applicable law.']}
 ]}/>;}
